rgName = "VWAN-Terraform"
unique_id = "moo"
vWANName = "VWAN-MooCorp"
vwanRegion = "westus"
vwanHubStartingOctect = 249
vnetSpokeStartingOctect = 250
adminUsername = "labadmin"
adminPassword = "YourSuperSecretPassword!"
hubRegions = [ "westus", "southeastasia" ]
OnSite-GW-PIPs = [ "123.123.123.123", "123.123.123.124" ]
OnSite-GW-Model = "ISR 2900"
OnSite-GW-Vendor = "Cisco"
OnSite-GW-StartingOctect = 10